const mutations = {
  IS_LOGGED_IN: 'IS_LOGGED_IN',
  IS_FIRST_LOGIN: 'IS_FIRST_LOGIN',
  LOGIN_LOADER: 'LOGIN_LOADER',
  SIGNUP_LOADER: 'SIGNUP_LOADER',
  RESET_PASSWORD_LOADER: 'RESET_PASSWORD_LOADER',
  SHOW_NOTIFY: 'SHOW_NOTIFY',
  USER: 'USER',
  PUBLIC_CHATS: 'PUBLIC_CHATS',
  SELECT_CHAT_ID: 'SELECT_CHAT_ID',
  CURRENT_CHAT: 'CURRENT_CHAT',
  CURRENT_CHAT_MSGS: 'CURRENT_CHAT_MSGS',
};

export default mutations;
